/*********************************************************************
*                   (c) SEGGER Microcontroller GmbH                  *
*                        The Embedded Experts                        *
*                           www.segger.com                           *
**********************************************************************

----------------------------------------------------------------------
Licensing information

Licensor:                 SEGGER Microcontroller Systems LLC
Licensed to:              React Health Inc., 203 Avenue A NW, Suite 300, Winter Haven FL 33881, USA
Licensed SEGGER software: emFile
License number:           FS-00855
License model:            SSL [Single Developer Single Platform Source Code License]
Licensed product:         -
Licensed platform:        STM32F4, IAR
Licensed number of seats: 1
-------------------------- END-OF-HEADER -----------------------------

File    : FS_NOR_HW_SPI_STM32H735_Morpheus.c
Purpose : Low-level flash driver for STM32H7 SPI interface.
*/

/*********************************************************************
*
*       #include section
*
**********************************************************************
*/
#include "FS.h"
#include "FS_OS.h"
#include "main.h"
#include "RTOS.h"

/*********************************************************************
*
*      Defines, configurable
*
**********************************************************************
*/
#ifndef   FS_NOR_HW_USE_DMA
  #define FS_NOR_HW_USE_DMA             1                           // Enables/disables the data transfer via DMA.
#endif

#ifndef   FS_NOR_HW_PER_CLK_HZ
  #define FS_NOR_HW_PER_CLK_HZ          (200000000uL / 2)           // Clock of SPI peripheral
#endif

#ifndef   FS_NOR_HW_NOR_CLK_HZ
  #define FS_NOR_HW_NOR_CLK_HZ          FS_NOR_HW_PER_CLK_HZ        // Frequency of the clock supplied to NOR flash device
#endif

/*********************************************************************
*
*       #include section, conditional
*
**********************************************************************
*/

/*********************************************************************
*
*       Defines, non-configurable
*
**********************************************************************
*/

/*********************************************************************
*
*       Misc. defines
*/
#define WAIT_TIMEOUT_MS                 1000                        // how much time to wait before timing out

/*********************************************************************
*
*      Static data
*
**********************************************************************
*/
static U8   _IsInited = 0;
static U32  _Freq_Hz  = 0;

/*********************************************************************
*
*      Static code
*
**********************************************************************
*/

/*********************************************************************
*
*       _HW_Init
*
*  Function description
*    HW layer function. It is called before any other function of the physical layer.
*    It should configure the HW so that the other functions can access the NOR flash.
*
*  Return value
*    Frequency of the SPI clock in kHz.
*/
static int _HW_Init(U8 Unit) {
  FS_USE_PARA(Unit);
  if (_IsInited == 0) {
    _Freq_Hz = FS_NOR_HW_NOR_CLK_HZ;
    //
    // Utilize HAL init function generated by CubeMX
    //
    MX_SPI4_Init();
    
    _IsInited = 1;
  }
  return (int)_Freq_Hz / 1000;
}

/*********************************************************************
*
*       _HW_EnableCS
*
*  Function description
*    Activates chip select signal (CS) of the NOR flash chip.
*
*  Parameters
*    Unit   Device index
*/
static void _HW_EnableCS(U8 Unit) {
  FS_USE_PARA(Unit);
  HAL_GPIO_WritePin(MAIN_NVM_CS_n_GPIO_Port, MAIN_NVM_CS_n_Pin, GPIO_PIN_RESET);
}

/*********************************************************************
*
*       _HW_DisableCS
*
*  Function description
*    Deactivates chip select signal (CS) of the NOR flash chip.
*
*  Parameters
*    Unit   Device index
*/
static void _HW_DisableCS(U8 Unit) {
  FS_USE_PARA(Unit);
  HAL_GPIO_WritePin(MAIN_NVM_CS_n_GPIO_Port, MAIN_NVM_CS_n_Pin, GPIO_PIN_SET);
}

/*********************************************************************
*
*       _HW_Read
*
*  Function description
*    Reads a specified number of bytes from NOR flash to buffer.
*
*  Parameters
*    Unit       Device index
*    pData      Pointer to a data buffer
*    NumBytes   Number of bytes to be read
*/
static void _HW_Read(U8 Unit, U8 * pData, int NumBytes) {
  FS_USE_PARA(Unit);
#if FS_NOR_HW_USE_DMA
  HAL_SPI_Receive_DMA(&hspi4, pData, NumBytes);
  FS_X_OS_Wait(WAIT_TIMEOUT_MS);
#else
  do {
    HAL_SPI_Receive(&hspi4, pData, 1, WAIT_TIMEOUT_MS);
    *pData++;
  } while (--NumBytes);
#endif
}

/*********************************************************************
*
*       _HW_Write
*
*  Function description
*    Writes a specified number of bytes from data buffer to NOR flash.
*
*  Parameters
*    Unit       Device index
*    pData      Pointer to a data buffer
*    NumBytes   Number of bytes to be written
*/
static void _HW_Write(U8 Unit, const U8 * pData, int NumBytes) {  
  FS_USE_PARA(Unit);
#if FS_NOR_HW_USE_DMA
  HAL_SPI_Transmit_DMA(&hspi4, pData, NumBytes);
  FS_X_OS_Wait(WAIT_TIMEOUT_MS);
#else
  do {
    HAL_SPI_Transmit(&hspi4, pData, 1, WAIT_TIMEOUT_MS);
    *pData++;
  } while (--NumBytes);
#endif
}

/*********************************************************************
*
*       _HW_Delay
*
*  Function description
*    Blocks the execution for the specified time.
*
*  Parameters
*    Unit       Index of the hardware layer (0-based).
*    ms         Number of milliseconds to block the execution.
*
*  Return value
*    ==0    OK, delay executed.
*    < 0    Functionality not supported.
*/
static int _HW_Delay(U8 Unit, U32 ms) {
  int r;

  FS_USE_PARA(Unit);
  r = -1;                   // Set to indicate that the feature is not supported.
  if (ms) {
    FS_X_OS_Delay(ms);
    r = 0;
  }
  return r;
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

/**********************************************************
*
*       HAL_SPI_RxCpltCallback
*
*  Function description
*    Handles the SPI Receive Complete interrupt
*/
void HAL_SPI_RxCpltCallback(SPI_HandleTypeDef *hspi) {
  OS_EnterNestableInterrupt();  // Inform embOS that interrupt code is running.
  if (hspi == &hspi4) {
    FS_X_OS_Signal();
  }
  OS_LeaveNestableInterrupt();  // Inform embOS that interrupt code is left.
}

/**********************************************************
*
*       HAL_SPI_TxCpltCallback
*
*  Function description
*    Handles the SPI Receive Complete interrupt
*/
void HAL_SPI_TxCpltCallback(SPI_HandleTypeDef *hspi) {
  OS_EnterNestableInterrupt();  // Inform embOS that interrupt code is running.
  if (hspi == &hspi4) {
    FS_X_OS_Signal();
  }
  OS_LeaveNestableInterrupt();  // Inform embOS that interrupt code is left.
}


/*********************************************************************
*
*       HAL_SPI_RxCpltCallback
*/

/*********************************************************************
*
*       HAL_SPI_TxCpltCallback
*/

/*********************************************************************
*
*       Global data
*
**********************************************************************
*/
const FS_NOR_HW_TYPE_SPI FS_NOR_HW_SPI_STM32H735_Morpheus = {
  _HW_Init,
  _HW_EnableCS,
  _HW_DisableCS,
  _HW_Read,
  _HW_Write,
  NULL,
  NULL,
  NULL,
  NULL,
  _HW_Delay,
  NULL,
  NULL,
  NULL,
  NULL
};

/*************************** End of file ****************************/
